// recipes/vue/src/pages/Page.vue
<script setup lang="ts">
import { Render } from "@puckeditor/vue";
import "@puckeditor/vue/puck.css";
import { config, initialData } from "../puck.config";

const KEY = "puck-vue-recipe";
const data = JSON.parse(localStorage.getItem(KEY) || "null") || initialData;
</script>

<template>
  <div>
    <nav style="padding: 12px 24px; border-bottom: 1px solid #eee">
      <router-link to="/edit">Edit this page →</router-link>
    </nav>
    <Render :config="config" :data="data" />
  </div>
</template>

// recipes/svelte/src/pages/Page.svelte
<script lang="ts">
  import { Render } from "@puckeditor/svelte";
  import "@puckeditor/svelte/puck.css";
  import { config, initialData } from "../puck.config";

  const KEY = "puck-svelte-recipe";
  const data = JSON.parse(localStorage.getItem(KEY) || "null") || initialData;
</script>

<div>
  <nav style="padding: 12px 24px; border-bottom: 1px solid #eee">
    <a href="/edit">Edit this page →</a>
  </nav>
  <Render {config} {data} />
</div>
