// apps/demo-vue/src/pages/EditPage.vue
<script setup lang="ts">
import { useRouter } from "vue-router";
import { Puck, type PuckApi } from "@puckeditor/vue";
import "@puckeditor/vue/puck.css";
import { config } from "../puck/config";
import { loadData, saveData } from "../puck/data";

const router = useRouter();

// No `app` prop needed: bridged components inherit this app's context (Pinia,
// router, …) by default, so CounterBadge can read the store directly.
const initialData = loadData();

function onChange(data: unknown) {
  saveData(data);
}

function onPublish(data: unknown) {
  saveData(data);
  router.push("/");
}

function onReady(getPuck: () => PuckApi) {
  // The imperative PuckApi accessor.
  (window as any).__getPuck = getPuck;
}
</script>

<template>
  <div class="editor">
    <Puck
      :config="config"
      :data="initialData"
      header-title="Puck + Vue demo"
      @change="onChange"
      @publish="onPublish"
      @ready="onReady"
    />
  </div>
</template>

<style scoped>
.editor {
  height: 100vh;
}
</style>

// apps/demo-svelte/src/pages/EditPage.svelte
<script>
  import { Puck } from "@puckeditor/svelte";
  import "@puckeditor/svelte/puck.css";
  import { config } from "../puck/config";
  import { loadData, saveData } from "../puck/data";
  import { counterStore, COUNTER_KEY } from "../store.svelte";

  // A Map of app-level context, threaded into every bridged Svelte mount so
  // CounterBadge can read the store (analogue of demo-vue's `app` prop).
  const context = new Map([[COUNTER_KEY, counterStore]]);
  const initialData = loadData();

  const onchange = (data) => saveData(data);
  const onpublish = (data) => {
    saveData(data);
    location.href = "/";
  };
  const onready = (getPuck) => {
    // The imperative PuckApi accessor.
    window.__getPuck = getPuck;
  };
</script>

<div class="editor">
  <Puck
    {config}
    data={initialData}
    {context}
    headerTitle="Puck + Svelte demo"
    {onchange}
    {onpublish}
    {onready}
  />
</div>

<style>
  .editor {
    height: 100vh;
  }
</style>
