// recipes/svelte/src/pages/Editor.svelte
<script lang="ts">
  import { Puck } from "@puckeditor/svelte";
  import "@puckeditor/svelte/puck.css";
  import { config, initialData } from "../puck.config";

  const KEY = "puck-svelte-recipe";
  const data = JSON.parse(localStorage.getItem(KEY) || "null") || initialData;

  function onpublish(next: unknown) {
    localStorage.setItem(KEY, JSON.stringify(next));
    location.assign("/");
  }
</script>

<div style="height: 100vh">
  <Puck {config} {data} {onpublish} />
</div>

// recipes/vue/src/pages/Editor.vue
<script setup lang="ts">
import { useRouter } from "vue-router";
import { Puck } from "@puckeditor/vue";
import "@puckeditor/vue/puck.css";
import { config, initialData } from "../puck.config";

const router = useRouter();

const KEY = "puck-vue-recipe";
const data = JSON.parse(localStorage.getItem(KEY) || "null") || initialData;

function onPublish(next: unknown) {
  localStorage.setItem(KEY, JSON.stringify(next));
  router.push("/");
}
</script>

<template>
  <div style="height: 100vh">
    <Puck :config="config" :data="data" @publish="onPublish" />
  </div>
</template>
