// apps/demo-svelte/src/puck/components/Columns.svelte
<script>
  // `items` is a slot field. Instead of a prop, render it with <PuckSlot name>;
  // Puck portals the (editable) DropZone into the placeholder.
  import { PuckSlot } from "@puckeditor/svelte";

  let { columns = 2 } = $props();
</script>

<div
  class="columns"
  style="grid-template-columns: repeat({columns || 2}, 1fr)"
>
  <PuckSlot name="items" class="columns-slot" />
</div>

<style>
  .columns {
    display: grid;
    gap: 12px;
    padding: 12px;
  }
</style>

// apps/demo-vue/src/puck/components/Columns.vue
<script setup lang="ts">
import type { Component } from "vue";

// `items` is a slot field. The bridge passes a stable outlet component; render
// it with `<component :is>` and Puck portals the (editable) DropZone into it.
defineProps<{ items?: Component; columns?: number }>();
</script>

<template>
  <div class="columns" :style="{ gridTemplateColumns: `repeat(${columns || 2}, 1fr)` }">
    <component :is="items" class="columns-slot" />
  </div>
</template>

<style scoped>
.columns {
  display: grid;
  gap: 12px;
  padding: 12px;
}
.columns-slot {
  border: 1px dashed #cbd5e1;
  border-radius: 6px;
  min-height: 64px;
}
</style>
