// apps/demo-svelte/src/puck/components/Heading.svelte
<script>
  // `title` is a contentEditable text field. Core swaps its value for an inline
  // editor element in the editor (a plain string in <Render>), so render it via
  // <PuckText>, which bridges the value in.
  import { PuckText } from "@puckeditor/svelte";
</script>

<h1 class="heading"><PuckText name="title" /></h1>

<style>
  .heading {
    margin: 0;
    padding: 24px;
    font-size: 2rem;
  }
</style>

// apps/demo-vue/src/puck/components/Heading.vue
<script setup lang="ts">
import type { Component } from "vue";

// `title` is a contentEditable text field. Core swaps its value for an inline
// editor element in the editor (a plain string in <Render>), so the bridge
// passes it as an outlet — render it with `<component :is>`, like a slot.
defineProps<{ title?: string | Component }>();
</script>

<template>
  <h1 class="heading"><component :is="title" /></h1>
</template>

<style scoped>
.heading {
  margin: 0;
  padding: 24px;
  font-size: 2rem;
}
</style>
